<?php
// $Name$

/**
 * @file
 * getdirections module installation.
 */

/**
 * Implementation of hook_uninstall().
  */
function getdirections_uninstall() {
  variable_del('getdirections_default');
  variable_del('getdirections_api_key');
  variable_del('getdirections_use_v3');
  variable_del('getdirections_misc');
}

function getdirections_update_6000() {
  $g3 = variable_get('use_v3', 0);
  variable_set('getdirections_use_v3', $g3);
  variable_del('use_v3');
  return array();
}
